# Site settings
description: A blog about Jonas Cheng
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonascheng.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jonas Cheng
user_description: 
user_title: Software Development Manager
email: jonas.cheng@gmail.com
twitter_username: 
github_username:  jonascheng
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
#  - title: Series
#    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
